# coding: utf-8

"""
Copyright 2015 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class LogService100LogService(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        LogService100LogService - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'odata_context': 'Odata400Context',
            'odata_id': 'Odata400Id',
            'odata_type': 'Odata400Type',
            'actions': 'LogService100LogServiceActions',
            'description': 'ResourceDescription',
            'entries': 'LogEntryCollectionLogEntryCollection',
            'id': 'ResourceId',
            'max_number_of_records': 'float',
            'name': 'ResourceName',
            'oem': 'ResourceOem',
            'over_write_policy': 'LogService100OverWritePolicy',
            'status': 'ResourceStatus'
        }

        self.attribute_map = {
            'odata_context': '@odata.context',
            'odata_id': '@odata.id',
            'odata_type': '@odata.type',
            'actions': 'Actions',
            'description': 'Description',
            'entries': 'Entries',
            'id': 'Id',
            'max_number_of_records': 'MaxNumberOfRecords',
            'name': 'Name',
            'oem': 'Oem',
            'over_write_policy': 'OverWritePolicy',
            'status': 'Status'
        }

        self._odata_context = None
        self._odata_id = None
        self._odata_type = None
        self._actions = None
        self._description = None
        self._entries = None
        self._id = None
        self._max_number_of_records = None
        self._name = None
        self._oem = None
        self._over_write_policy = None
        self._status = None

    @property
    def odata_context(self):
        """
        Gets the odata_context of this LogService100LogService.


        :return: The odata_context of this LogService100LogService.
        :rtype: Odata400Context
        """
        return self._odata_context

    @odata_context.setter
    def odata_context(self, odata_context):
        """
        Sets the odata_context of this LogService100LogService.


        :param odata_context: The odata_context of this LogService100LogService.
        :type: Odata400Context
        """
        self._odata_context = odata_context

    @property
    def odata_id(self):
        """
        Gets the odata_id of this LogService100LogService.


        :return: The odata_id of this LogService100LogService.
        :rtype: Odata400Id
        """
        return self._odata_id

    @odata_id.setter
    def odata_id(self, odata_id):
        """
        Sets the odata_id of this LogService100LogService.


        :param odata_id: The odata_id of this LogService100LogService.
        :type: Odata400Id
        """
        self._odata_id = odata_id

    @property
    def odata_type(self):
        """
        Gets the odata_type of this LogService100LogService.


        :return: The odata_type of this LogService100LogService.
        :rtype: Odata400Type
        """
        return self._odata_type

    @odata_type.setter
    def odata_type(self, odata_type):
        """
        Sets the odata_type of this LogService100LogService.


        :param odata_type: The odata_type of this LogService100LogService.
        :type: Odata400Type
        """
        self._odata_type = odata_type

    @property
    def actions(self):
        """
        Gets the actions of this LogService100LogService.


        :return: The actions of this LogService100LogService.
        :rtype: LogService100LogServiceActions
        """
        return self._actions

    @actions.setter
    def actions(self, actions):
        """
        Sets the actions of this LogService100LogService.


        :param actions: The actions of this LogService100LogService.
        :type: LogService100LogServiceActions
        """
        self._actions = actions

    @property
    def description(self):
        """
        Gets the description of this LogService100LogService.


        :return: The description of this LogService100LogService.
        :rtype: ResourceDescription
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this LogService100LogService.


        :param description: The description of this LogService100LogService.
        :type: ResourceDescription
        """
        self._description = description

    @property
    def entries(self):
        """
        Gets the entries of this LogService100LogService.
        References to the log entry collection.

        :return: The entries of this LogService100LogService.
        :rtype: LogEntryCollectionLogEntryCollection
        """
        return self._entries

    @entries.setter
    def entries(self, entries):
        """
        Sets the entries of this LogService100LogService.
        References to the log entry collection.

        :param entries: The entries of this LogService100LogService.
        :type: LogEntryCollectionLogEntryCollection
        """
        self._entries = entries

    @property
    def id(self):
        """
        Gets the id of this LogService100LogService.


        :return: The id of this LogService100LogService.
        :rtype: ResourceId
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this LogService100LogService.


        :param id: The id of this LogService100LogService.
        :type: ResourceId
        """
        self._id = id

    @property
    def max_number_of_records(self):
        """
        Gets the max_number_of_records of this LogService100LogService.
        The maximum number of log entries this service can have.

        :return: The max_number_of_records of this LogService100LogService.
        :rtype: float
        """
        return self._max_number_of_records

    @max_number_of_records.setter
    def max_number_of_records(self, max_number_of_records):
        """
        Sets the max_number_of_records of this LogService100LogService.
        The maximum number of log entries this service can have.

        :param max_number_of_records: The max_number_of_records of this LogService100LogService.
        :type: float
        """
        self._max_number_of_records = max_number_of_records

    @property
    def name(self):
        """
        Gets the name of this LogService100LogService.


        :return: The name of this LogService100LogService.
        :rtype: ResourceName
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this LogService100LogService.


        :param name: The name of this LogService100LogService.
        :type: ResourceName
        """
        self._name = name

    @property
    def oem(self):
        """
        Gets the oem of this LogService100LogService.
        This is the manufacturer/provider specific extension moniker used to divide the Oem object into sections.

        :return: The oem of this LogService100LogService.
        :rtype: ResourceOem
        """
        return self._oem

    @oem.setter
    def oem(self, oem):
        """
        Sets the oem of this LogService100LogService.
        This is the manufacturer/provider specific extension moniker used to divide the Oem object into sections.

        :param oem: The oem of this LogService100LogService.
        :type: ResourceOem
        """
        self._oem = oem

    @property
    def over_write_policy(self):
        """
        Gets the over_write_policy of this LogService100LogService.
        The overwrite policy for this service that takes place when the log is full.

        :return: The over_write_policy of this LogService100LogService.
        :rtype: LogService100OverWritePolicy
        """
        return self._over_write_policy

    @over_write_policy.setter
    def over_write_policy(self, over_write_policy):
        """
        Sets the over_write_policy of this LogService100LogService.
        The overwrite policy for this service that takes place when the log is full.

        :param over_write_policy: The over_write_policy of this LogService100LogService.
        :type: LogService100OverWritePolicy
        """
        self._over_write_policy = over_write_policy

    @property
    def status(self):
        """
        Gets the status of this LogService100LogService.


        :return: The status of this LogService100LogService.
        :rtype: ResourceStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """
        Sets the status of this LogService100LogService.


        :param status: The status of this LogService100LogService.
        :type: ResourceStatus
        """
        self._status = status

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other): 
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """ 
        Returns true if both objects are not equal
        """
        return not self == other

