# coding: utf-8

"""
Copyright 2015 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class Manager100ManagerActions(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        Manager100ManagerActions - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'manager_modify_redundancy_set': 'Manager100ModifyRedundancySet',
            'manager_reset': 'Manager100Reset',
            'oem': 'object',
            'manager_force_failover': 'Manager100ForceFailover'
        }

        self.attribute_map = {
            'manager_modify_redundancy_set': '#Manager.ModifyRedundancySet',
            'manager_reset': '#Manager.Reset',
            'oem': 'Oem',
            'manager_force_failover': '#Manager.ForceFailover'
        }

        self._manager_modify_redundancy_set = None
        self._manager_reset = None
        self._oem = None
        self._manager_force_failover = None

    @property
    def manager_modify_redundancy_set(self):
        """
        Gets the manager_modify_redundancy_set of this Manager100ManagerActions.


        :return: The manager_modify_redundancy_set of this Manager100ManagerActions.
        :rtype: Manager100ModifyRedundancySet
        """
        return self._manager_modify_redundancy_set

    @manager_modify_redundancy_set.setter
    def manager_modify_redundancy_set(self, manager_modify_redundancy_set):
        """
        Sets the manager_modify_redundancy_set of this Manager100ManagerActions.


        :param manager_modify_redundancy_set: The manager_modify_redundancy_set of this Manager100ManagerActions.
        :type: Manager100ModifyRedundancySet
        """
        self._manager_modify_redundancy_set = manager_modify_redundancy_set

    @property
    def manager_reset(self):
        """
        Gets the manager_reset of this Manager100ManagerActions.


        :return: The manager_reset of this Manager100ManagerActions.
        :rtype: Manager100Reset
        """
        return self._manager_reset

    @manager_reset.setter
    def manager_reset(self, manager_reset):
        """
        Sets the manager_reset of this Manager100ManagerActions.


        :param manager_reset: The manager_reset of this Manager100ManagerActions.
        :type: Manager100Reset
        """
        self._manager_reset = manager_reset

    @property
    def oem(self):
        """
        Gets the oem of this Manager100ManagerActions.


        :return: The oem of this Manager100ManagerActions.
        :rtype: object
        """
        return self._oem

    @oem.setter
    def oem(self, oem):
        """
        Sets the oem of this Manager100ManagerActions.


        :param oem: The oem of this Manager100ManagerActions.
        :type: object
        """
        self._oem = oem

    @property
    def manager_force_failover(self):
        """
        Gets the manager_force_failover of this Manager100ManagerActions.


        :return: The manager_force_failover of this Manager100ManagerActions.
        :rtype: Manager100ForceFailover
        """
        return self._manager_force_failover

    @manager_force_failover.setter
    def manager_force_failover(self, manager_force_failover):
        """
        Sets the manager_force_failover of this Manager100ManagerActions.


        :param manager_force_failover: The manager_force_failover of this Manager100ManagerActions.
        :type: Manager100ForceFailover
        """
        self._manager_force_failover = manager_force_failover

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other): 
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """ 
        Returns true if both objects are not equal
        """
        return not self == other

