# coding: utf-8

"""
Copyright 2015 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class RackHDBootImageNetworkDevice(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        RackHDBootImageNetworkDevice - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'device': 'str',
            'ipv4': 'RackHDBootImageNetworkAddress',
            'ipv6': 'RackHDBootImageNetworkAddress'
        }

        self.attribute_map = {
            'device': 'device',
            'ipv4': 'ipv4',
            'ipv6': 'ipv6'
        }

        self._device = None
        self._ipv4 = None
        self._ipv6 = None

    @property
    def device(self):
        """
        Gets the device of this RackHDBootImageNetworkDevice.
        The name of the network device.

        :return: The device of this RackHDBootImageNetworkDevice.
        :rtype: str
        """
        return self._device

    @device.setter
    def device(self, device):
        """
        Sets the device of this RackHDBootImageNetworkDevice.
        The name of the network device.

        :param device: The device of this RackHDBootImageNetworkDevice.
        :type: str
        """
        self._device = device

    @property
    def ipv4(self):
        """
        Gets the ipv4 of this RackHDBootImageNetworkDevice.
        This the ipv4 parameter of the network device.

        :return: The ipv4 of this RackHDBootImageNetworkDevice.
        :rtype: RackHDBootImageNetworkAddress
        """
        return self._ipv4

    @ipv4.setter
    def ipv4(self, ipv4):
        """
        Sets the ipv4 of this RackHDBootImageNetworkDevice.
        This the ipv4 parameter of the network device.

        :param ipv4: The ipv4 of this RackHDBootImageNetworkDevice.
        :type: RackHDBootImageNetworkAddress
        """
        self._ipv4 = ipv4

    @property
    def ipv6(self):
        """
        Gets the ipv6 of this RackHDBootImageNetworkDevice.
        This is the ipv6 parameter of the network device.

        :return: The ipv6 of this RackHDBootImageNetworkDevice.
        :rtype: RackHDBootImageNetworkAddress
        """
        return self._ipv6

    @ipv6.setter
    def ipv6(self, ipv6):
        """
        Sets the ipv6 of this RackHDBootImageNetworkDevice.
        This is the ipv6 parameter of the network device.

        :param ipv6: The ipv6 of this RackHDBootImageNetworkDevice.
        :type: RackHDBootImageNetworkAddress
        """
        self._ipv6 = ipv6

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other): 
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """ 
        Returns true if both objects are not equal
        """
        return not self == other

