# coding: utf-8

"""
Copyright 2015 SmartBear Software

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

    Ref: https://github.com/swagger-api/swagger-codegen
"""

from pprint import pformat
from six import iteritems


class SerialInterfaceCollectionSerialInterfaceCollection(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self):
        """
        SerialInterfaceCollectionSerialInterfaceCollection - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'odata_context': 'Odata400Context',
            'odata_id': 'Odata400Id',
            'odata_type': 'Odata400Type',
            'description': 'ResourceDescription',
            'members': 'list[SerialInterfaceSerialInterface]',
            'membersodata_count': 'Odata400Count',
            'membersodata_navigation_link': 'Odata400IdRef',
            'name': 'ResourceName',
            'oem': 'ResourceOem'
        }

        self.attribute_map = {
            'odata_context': '@odata.context',
            'odata_id': '@odata.id',
            'odata_type': '@odata.type',
            'description': 'Description',
            'members': 'Members',
            'membersodata_count': 'Members@odata.count',
            'membersodata_navigation_link': 'Members@odata.navigationLink',
            'name': 'Name',
            'oem': 'Oem'
        }

        self._odata_context = None
        self._odata_id = None
        self._odata_type = None
        self._description = None
        self._members = None
        self._membersodata_count = None
        self._membersodata_navigation_link = None
        self._name = None
        self._oem = None

    @property
    def odata_context(self):
        """
        Gets the odata_context of this SerialInterfaceCollectionSerialInterfaceCollection.


        :return: The odata_context of this SerialInterfaceCollectionSerialInterfaceCollection.
        :rtype: Odata400Context
        """
        return self._odata_context

    @odata_context.setter
    def odata_context(self, odata_context):
        """
        Sets the odata_context of this SerialInterfaceCollectionSerialInterfaceCollection.


        :param odata_context: The odata_context of this SerialInterfaceCollectionSerialInterfaceCollection.
        :type: Odata400Context
        """
        self._odata_context = odata_context

    @property
    def odata_id(self):
        """
        Gets the odata_id of this SerialInterfaceCollectionSerialInterfaceCollection.


        :return: The odata_id of this SerialInterfaceCollectionSerialInterfaceCollection.
        :rtype: Odata400Id
        """
        return self._odata_id

    @odata_id.setter
    def odata_id(self, odata_id):
        """
        Sets the odata_id of this SerialInterfaceCollectionSerialInterfaceCollection.


        :param odata_id: The odata_id of this SerialInterfaceCollectionSerialInterfaceCollection.
        :type: Odata400Id
        """
        self._odata_id = odata_id

    @property
    def odata_type(self):
        """
        Gets the odata_type of this SerialInterfaceCollectionSerialInterfaceCollection.


        :return: The odata_type of this SerialInterfaceCollectionSerialInterfaceCollection.
        :rtype: Odata400Type
        """
        return self._odata_type

    @odata_type.setter
    def odata_type(self, odata_type):
        """
        Sets the odata_type of this SerialInterfaceCollectionSerialInterfaceCollection.


        :param odata_type: The odata_type of this SerialInterfaceCollectionSerialInterfaceCollection.
        :type: Odata400Type
        """
        self._odata_type = odata_type

    @property
    def description(self):
        """
        Gets the description of this SerialInterfaceCollectionSerialInterfaceCollection.


        :return: The description of this SerialInterfaceCollectionSerialInterfaceCollection.
        :rtype: ResourceDescription
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this SerialInterfaceCollectionSerialInterfaceCollection.


        :param description: The description of this SerialInterfaceCollectionSerialInterfaceCollection.
        :type: ResourceDescription
        """
        self._description = description

    @property
    def members(self):
        """
        Gets the members of this SerialInterfaceCollectionSerialInterfaceCollection.
        Contains the members of this collection.

        :return: The members of this SerialInterfaceCollectionSerialInterfaceCollection.
        :rtype: list[SerialInterfaceSerialInterface]
        """
        return self._members

    @members.setter
    def members(self, members):
        """
        Sets the members of this SerialInterfaceCollectionSerialInterfaceCollection.
        Contains the members of this collection.

        :param members: The members of this SerialInterfaceCollectionSerialInterfaceCollection.
        :type: list[SerialInterfaceSerialInterface]
        """
        self._members = members

    @property
    def membersodata_count(self):
        """
        Gets the membersodata_count of this SerialInterfaceCollectionSerialInterfaceCollection.


        :return: The membersodata_count of this SerialInterfaceCollectionSerialInterfaceCollection.
        :rtype: Odata400Count
        """
        return self._membersodata_count

    @membersodata_count.setter
    def membersodata_count(self, membersodata_count):
        """
        Sets the membersodata_count of this SerialInterfaceCollectionSerialInterfaceCollection.


        :param membersodata_count: The membersodata_count of this SerialInterfaceCollectionSerialInterfaceCollection.
        :type: Odata400Count
        """
        self._membersodata_count = membersodata_count

    @property
    def membersodata_navigation_link(self):
        """
        Gets the membersodata_navigation_link of this SerialInterfaceCollectionSerialInterfaceCollection.


        :return: The membersodata_navigation_link of this SerialInterfaceCollectionSerialInterfaceCollection.
        :rtype: Odata400IdRef
        """
        return self._membersodata_navigation_link

    @membersodata_navigation_link.setter
    def membersodata_navigation_link(self, membersodata_navigation_link):
        """
        Sets the membersodata_navigation_link of this SerialInterfaceCollectionSerialInterfaceCollection.


        :param membersodata_navigation_link: The membersodata_navigation_link of this SerialInterfaceCollectionSerialInterfaceCollection.
        :type: Odata400IdRef
        """
        self._membersodata_navigation_link = membersodata_navigation_link

    @property
    def name(self):
        """
        Gets the name of this SerialInterfaceCollectionSerialInterfaceCollection.


        :return: The name of this SerialInterfaceCollectionSerialInterfaceCollection.
        :rtype: ResourceName
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this SerialInterfaceCollectionSerialInterfaceCollection.


        :param name: The name of this SerialInterfaceCollectionSerialInterfaceCollection.
        :type: ResourceName
        """
        self._name = name

    @property
    def oem(self):
        """
        Gets the oem of this SerialInterfaceCollectionSerialInterfaceCollection.
        This is the manufacturer/provider specific extension moniker used to divide the Oem object into sections.

        :return: The oem of this SerialInterfaceCollectionSerialInterfaceCollection.
        :rtype: ResourceOem
        """
        return self._oem

    @oem.setter
    def oem(self, oem):
        """
        Sets the oem of this SerialInterfaceCollectionSerialInterfaceCollection.
        This is the manufacturer/provider specific extension moniker used to divide the Oem object into sections.

        :param oem: The oem of this SerialInterfaceCollectionSerialInterfaceCollection.
        :type: ResourceOem
        """
        self._oem = oem

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other): 
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """ 
        Returns true if both objects are not equal
        """
        return not self == other

